### ISSUE TITLE
Question: How to run a single set of test cases or single test case

### ISSUE THREAD

**Issue by RobertoIDL** [square/spoon#253]
Hi,

I spent all day setting Spoon and so far so good. There is just one thing I can seem to make to work, I want to run a single test case ( a method inside one of my test classes). I've tried using this:

gradlew spoon -PspoonClassName=the.class.path

But it didn't do anything, it ended up running all of them.

Is there a simple way of running only one test case? this would speed up my coding a lot. 

Thanks!

**Comment by vgrec** [comment]
I didn't do it myselft, but according to the docs, you should run spoon with the following parameter:
-Dspoon.test.method=myTestMethod

**Comment by RobertoIDL** [comment]
Thanks for the quick response, I'll give it a go.

I may have missed it, what docs are you referring to?

**Comment by vgrec** [comment]
This: http://square.github.io/spoon/, see somewhere at the end of the page is mentioned how to run a specific method or test class.

**Comment by RobertoIDL** [comment]
Must be me but I can't make this to work.

I'm trying the following:

gradlew spoon -Dspoon.test.class=com.mypackage.tests.instrumentation.MainActivityTest

That runs all the test cases in all my test classes.

I have also tried specifying a test method like this:

gradlew spoon -Dspoon.test.method=testInvalidEmail

Same result as before, all test are run.

Am I missing something?

Thanks.

**Comment by roman-mazur** [comment]
`-Dspoon.test.method` will work when you run spoon tests with Maven. This is what is said in the referred documentation.
You run them with Gradle though. If you use https://github.com/stanfy/spoon-gradle-plugin, setting this property will not work. Instead gradle plugin provides its own means [to define a single test to run](https://github.com/stanfy/spoon-gradle-plugin#usage). If you want to supply this from the command line you may use the [approach illustrated in the example](https://github.com/stanfy/spoon-gradle-plugin/blob/master/example/app/build.gradle#L38-L46) for this plugin.

I agree that the plugin should have been more friendly to what is described in the spoon docs and supported `spoon.test.method` as well. But since I (the main contributor to that plugin) have never run spoon tests with maven, this has not happened. PR is welcome!

**Comment by RobertoIDL** [comment]
I got confused between both plugins.

I've just made it to work using this approach:

// This section is optional
spoon {
  // for debug output
  debug = true

  // To run a single test class
  className = 'fully.qualified.TestCase'

  // To run a single method in TestCase
  methodName = 'testMyApp'
}

All sorted now, thank you.
