### ISSUE TITLE
Suggestion: Mode where if one device passes the test is marked pass

### ISSUE THREAD

**Issue by chthompson** [square/spoon#290]
Sometimes when I run tests one device will fail because of timing issue.  I would love a way to have the runner report pass when at least 1 device passes.  This may appear to be a stupid request but I'm finding I have some flaky tests so this would help with that.

**Comment by f2prateek** [comment]
I don't think this should be a flag. You should fix the flaky test instead.

**Comment by JakeWharton** [comment]
I am inclined to agree. Flaky tests promote the damaging behavior of ignoring test failures which might be legitimate. You need to have 100% confidence in your tests ability to exercise your app, otherwise I don't see how you could rely on them to correctly detect regressions. You should either work to fix the flaky test, or remove it. If it fails at a consistent rate, it is doing you little good.

**Comment by chthompson** [comment]
yes your right but I'm finding the combination of devices + OS + test often creates flakyness by nature.  I will work towards fixing things up I'm close.  I noticed for example some devices on some OS version have memory leaks in the OS version or something so it just only gets through about half the tests and then stops.  For now I just don't use that device :(  

But hey this Spoon runner is an amazing tool thanks for building it!
