### ISSUE TITLE
Continue test run in case of crash

### ISSUE THREAD

**Issue by originx** [square/spoon#372]
Currently if there is a fatal error during test execution entire test suite for that device fails.

It would be most useful to continue the test run, and probably mark the crashing test in explicit color so it catches the eye during reports.

**Comment by tir38** [comment]
What type of fatal error are you referring to? Can you ensure that the device/emulator is in the state you *think* it is if a fatal error occurred?

**Comment by originx** [comment]
If there is a runtime exception in the app during tests execution, test runner fails to recover, ie. will not continue the rest of the test suite.

Whilst normal android test runner can recover from these fatal errors, continues and finishes the rest of the test suite.

So by fatal error I mean:  a runtime exception or any kind of fatal issue that crashes the running app

**Comment by drywolf** [comment]
I would also be very interested in this functionality. I am using [stanfy/spoon-gradle-plugin](https://github.com/stanfy/spoon-gradle-plugin) to run tests on an android emulator and since there is some JNI code involved, crashes of tests are almost certain to happen during development.
If a single crash happens, then the rest of the test-suite will just not be run and the test result is therefore not as useful and can not be easily compared with the results of other test runs.

@JakeWharton Without having looked into the spoon code yet, I would assume that this feature would need some kind of restarting of the Test-Activity after it has crashed and after the restart it needs to pick up the test-run right after the test that crashed it before.
Can you see any big technical blockers that would make implementing this feature very hard ?
I am asking because if you would say that it would be feasable and could be done with reasonable effort then I will look into implementing this.

Please let me know what you think
Thanks 😃

**Comment by JakeWharton** [comment]
This is already implemented on master.

**Comment by drywolf** [comment]
Great, then I will look into [stanfy/spoon-gradle-plugin](https://github.com/stanfy/spoon-gradle-plugin) to see if I can get its spoon version upgraded. Thanks 👍

**Comment by dyloum84** [comment]
@JakeWharton How do you use it? 
My full test suite is stopping after a crash.
Thanks
