### ISSUE TITLE
screenshots only kept when running single test with 3.0 android gradle plugin

### ISSUE THREAD

**Issue by thadcodes** [square/spoon#478]
Please let me know if there is a correct way to test this but I've noticed with master that only screenshots from the last test are kept.  It seems like either deleting `deletePath(directory, false);` from the `SpoonRule.obtainScreenshotDirectory()` method or moving calls to `pullDeviceFiles` up inside the test loop in `SpoonDeviceRunner.run()` as shown below seems to fix the issue.  Not sure which is the correct fix or how it's properly tested.

```    
for (TestIdentifier test : activeTests) {
      logDebug(debug, "Running %s [%s]", test, serial);
      try {
        RemoteAndroidTestRunner runner = createConfiguredRunner(testPackage, testRunner, device);
        if (codeCoverage) {
          addCodeCoverageInstrumentationArgs(runner, device);
        }
        runner.setMethodName(test.getClassName(), test.getTestName());
        runner.run(listeners);
      } catch (Exception e) {
        result.addException(e);
        break;
      }

      try {
        pullDeviceFiles(device);
      } catch (Exception e) {
        result.addException(e);
      }
    }
```

**Comment by dweebo** [comment]
The problem appears to me to be in `SpoonRule.obtainScreenshotDirectory` as you pointed out.  I debugged it a bit and think it's because each test is run it's own process (perhaps because of https://github.com/square/spoon/pull/456, I don't see the issue when running with spoon before that PR but haven't narrowed it down more than that). 

This code is trying to make sure the spoon screenshots directory is only deleted once, for the first test in a test run per device. 
```
synchronized (LOCK) {
  if (clearedOutputDirectories.add(SPOON_SCREENSHOTS)) {
    deletePath(directory, false);
   }
}
```
But because each test runs in it's own process they each get their own static clearedOutputDirectories so it runs `deletePath` for each test.

As for a fix I don't think you'd want to `pullDeviceFiles` after each test for efficiency reasons.  Maybe spoon should just delete the screenshot directory somewhere else before the first test is run, perhaps in `SpoonDeviceRunner`.  I'll see if I can get that working and submit a PR.
